---
title: "My Storyboard at DACSS - frames"
bibliography: testVisual.bib
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard) # always
```

# Setup

## Intro {.sidebar}

Preparing the dashboard based on the instructions given at @magallanes_reyes_data_2022, and @aden-buie_flexdashboard_2026.

Row
-------------------------------------

### I know this is not nice, but wait till I finish the course


```{r}
## for del1Draft.rds
link1="https://github.com/DACSS-690V-SP26/hw-test/raw/main/del1Draft.rds"
readRDS(url(link1))
```



### I am doing my best but still much to learn

```{r}
## for del2Draft.rds
link2="https://github.com/DACSS-690V-SP26/hw-test/raw/main/del2Draft.rds"
readRDS(url(link2))
```


### This might be the worst plot, but...

```{r}
## for del3Draft.rds
link3="https://github.com/DACSS-690V-SP26/hw-test/raw/main/del3Draft.rds"
readRDS(url(link3))
```


### References
<div id="refs"></div>

---

# HW2

Row
-------------------------------------

### Plot 1: Three-Gear Cars are Dominant 
```{r}
library(ggplot2)
mtcars_gear=mtcars$gear|>table()|>as.data.frame()
plot_gear= ggplot(mtcars_gear, aes(x=factor(Var1), y=Freq, label=Freq)) +
  geom_bar(stat = 'identity', fill = "lightgrey") +
  geom_text(hjust=1,size=9, color='blue') + coord_flip() + labs(x='Gear', title = 'Count of Cars per GEAR', caption = "Source: mtcars data") + theme_classic() + theme(axis.title.x = element_blank(), axis.line.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank(), plot.title = element_text(face = "bold"), axis.title = element_text(face = "bold")) 
plot_gear
```



Row
-------------------------------------

### Plot 2: Few Cars have SIX or more Carburators 
```{r}
mtcars_carb = mtcars$carb|>table()|>as.data.frame()
plot_carb= ggplot(mtcars_carb, aes(x=factor(Var1), y=Freq, label = Freq)) +
  geom_bar(stat = 'identity', fill = "yellow") +
  geom_text(hjust=0.5,vjust = -0.5, size=4, color='black') + labs(x='CARB', title = 'Count of Cars per CARB', caption = "Source: mtcars data") + theme_classic() + theme(axis.title.y = element_blank(), axis.line.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank(), axis.title.x = element_text(face = "bold"), plot.title = element_text(face = "bold")) 
plot_carb
```

Row
-------------------------------------

### Plot 3: Only 5-gear cars utilize the 6 and 8 carburetor setups. 
```{r}
plot3 = ggplot(data=mtcars,aes(x=factor(cyl))) + geom_bar(fill = "yellow") + facet_grid(gear~carb,labeller = label_both) + geom_text(stat = "count",
    aes(label = scales::percent(after_stat(count / sum(count)))),hjust=0.5,vjust = 2, size=2, color='black', fontface = "bold") + labs(x='cylinders', title = 'Distribution of Cylinder Counts by Carburetors and Gears', caption = "Source: mtcars data") + theme_light()
plot3
```

---

# HW3

```{r setup-massdata, include=FALSE}
library(readxl)
mass_schools <- read_excel("ncesdata_MASS_202425.xlsx", skip = 10)
colnames(mass_schools) <- as.character(mass_schools[1, ])
mass_schools <- mass_schools[-1, ]
invisible(head(mass_schools))

invisible(str(mass_schools,width = 70,strict.width='cut'))
invisible(unique(mass_schools$Locale))

absoluteLocale=table(mass_schools$Locale,
                 useNA = "ifany") 


tableFreq=as.data.frame(absoluteLocale)


propT=prop.table(absoluteLocale)*100


names(tableFreq)=c("Locale","Count")
tableFreq$Percent=as.vector(propT)

library(ggplot2)

tableFreq$Locale <- factor(tableFreq$Locale,
                    levels = c("City, Large", "City, Midsize", "City, Small", "Suburban, Large", "Suburban, Midsize", "Suburban, Small", "Town, Distant", "Town, Fringe", "Rural, Distant", "Rural, Fringe"))
```

Row
-------------------------------------

### Categorical Plot: Massachusetts School Locale
```{r, echo=FALSE}
base= ggplot(data = tableFreq, 
             aes(x = reorder(Locale, Percent), y = Percent)) 
titleText='Where are Public Schools located?'
sub_titleText='Massachusetts - 2024-2025'
sourceText='Source: National Center for Education Statistics'

LABELS=paste0(round(tableFreq$Percent,2), '%')

plot1 = base + geom_col(fill ="gray") + labs(title=titleText, subtitle = sub_titleText, x =NULL, y = NULL,caption = sourceText) + theme_bw() + theme(axis.text.x = element_text(angle = 60, hjust = 1), axis.text.y = element_blank(), axis.ticks.y = element_blank()) + geom_text(vjust=-0.25, size = 3.5, aes(y = Percent ,label = LABELS)) 
plot1


```


Row
-------------------------------------

### Numeric Plot: 
```{r}
mass_schools$`Student Teacher Ratio` <- as.numeric(mass_schools$`Student Teacher Ratio`)
#summary(mass_schools$`Student Teacher Ratio`)

library(moments)

md=median(mass_schools$`Student Teacher Ratio` ,na.rm = TRUE)
mn=mean(mass_schools$`Student Teacher Ratio` ,na.rm = TRUE)
sk=skewness(mass_schools$`Student Teacher Ratio` ,na.rm = TRUE)

txtMean=paste0('Mean:',round(mn))
txtSkew=paste0('Skewness:',round(sk,2))
txtMedian=paste0('Median:',round(md,2))

base=ggplot(mass_schools, aes(x=0, y=`Student Teacher Ratio`))+theme_classic()
boxRatio=base + geom_boxplot() 

box_data <- ggplot_build(boxRatio)$data[[1]]

lower_whisker <- box_data$lower[1]  # numeric value of lower whisker
upper_whisker <- box_data$upper[1]  # numeric value of upper whisker

outliers <- box_data$outliers[[1]]

lowOcount <- sum(outliers < lower_whisker)
upperOcount <- sum(outliers > upper_whisker)

txtOutliersUp <- paste0("upper outlying schools: ", upperOcount)
txtOutliersLo <- paste0("lower outlying schools: ", lowOcount)

y_upper_label <- upper_whisker * 2.75
y_lower_label <- lower_whisker * 0.3

vio=base+geom_violin(trim=FALSE, fill="grey")

viobox=vio+ 
        scale_y_continuous(trans = scales::pseudo_log_trans(base = 10)) + 
        geom_boxplot(width=0.25,
                        outlier.color = 'red',
                        colour = 'white',
                        fill='black') + coord_flip()

viobox=viobox + theme(axis.text.y = element_blank(),
                      axis.ticks.y = element_blank(),
                      axis.title.y = element_blank(), 
                      axis.text.x = element_text(angle = 90)) + 
               # about the outliers       
                      annotate(geom = 'text',size=3,
                               label=txtOutliersUp,
                                y = y_upper_label,
                                x=0.1,color='red',
                                angle=0) +
                      annotate(geom = 'text', size=3, 
                               label=txtOutliersLo,
                                y = y_lower_label,
                                x=0.1,color='red',
                                angle=0) +
              # about the mean
              geom_hline(yintercept = mn,color='darkgreen',
                         linetype="dotted") +
              # about the mean
              annotate(geom = 'text',color='darkgreen',
                       fontface = "bold",
                       label=txtMean, # mean as text
                       x = 0.6,
                       y=mn+1,
                       angle=0)   +
                      annotate(geom = 'text',color='black', 
                               size=3, fontface = "bold",
                               label=txtMedian, # median as text
                                x = -.5,
                                y=md-.75,
                                angle=0) +
            labs(title= "Student Teacher Ratio", subtitle = "Massachusetts- 2024-2025", y = NULL,caption = sourceText)
viobox 
```

---

# HW4

### Cat-Cat Visualization 
```{r}
Mass_Arrests <- read_xlsx("Mass_Arrests.xlsx")
TypeRaceTable=table(Mass_Arrests$`Arrest Type`, Mass_Arrests$Race)
#TypeRaceTable

library(magrittr)
TypeRaceProp=prop.table(TypeRaceTable,
                            margin = 2)%>%round(.,3)
#TypeRaceProp

TypeRaceDF=as.data.frame(TypeRaceTable)
names(TypeRaceDF)=c("Type","Race","Counts")
#TypeRaceDF

TypeRaceDF$pctCol=100*as.data.frame(TypeRaceProp)[,3]
#TypeRaceDF

library(ggplot2)

library(dplyr)

race_totals <- TypeRaceDF %>%
  group_by(Race) %>%
  summarise(total_race = sum(Counts))

TypeRaceDF <- TypeRaceDF %>%
  left_join(race_totals, by = "Race")

TypeRaceDF$Race <- factor(
  TypeRaceDF$Race,
  levels = race_totals$Race[order(-race_totals$total_race)]
)

race_totals <- TypeRaceDF %>%
  group_by(Race) %>%
  summarise(total_race = sum(Counts))

TypeRaceDF$Race <- factor(
  TypeRaceDF$Race,
  levels = race_totals$Race[order(-race_totals$total_race)]
)

TypeRaceDF$Race <- factor(TypeRaceDF$Race, levels = rev(levels(TypeRaceDF$Race)))

TypeRaceDF <- TypeRaceDF %>%
  group_by(Type) %>%
  mutate(
    Prop = Counts / sum(Counts),
    pct_label = paste0(round(Prop * 100, 1), "%")
  ) %>%
  ungroup()

#install.packages("viridis")   
library(viridis)

TypeRaceDF <- TypeRaceDF %>%
  mutate(Type = recode(Type,
    "F" = "Felony",
    "M" = "Misdemeanor",
    "W" = "Warrant", 
    "O" = "Other"
  ))
TypeRaceDF <- TypeRaceDF %>%
  mutate(Race = recode(Race,
    "B" = "Black/African American",
    "W" = "White",
    "H" = "Hispanic",
    "I" = "American Indian or Alaskan Native", 
    "O" = "Asian or Pacific Islander", 
    "J" = "Middle Eastern or East Indian (South Asian)", 
    "U" = "Unknown", 
    "N" = "Not Applicable"
  ))


basecat6 <- ggplot(TypeRaceDF, aes(x = Type, y = Counts, fill = Race)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_fill_viridis_d(option = "cividis") +
  geom_text(
  aes(label = ifelse(Prop > 0.05, pct_label, "")),
  position = position_fill(vjust = 0.5),
  size = 3) + 
   labs(title = "Arrrest Distribution by Type and Race",
                 subtitle = "Massachusetts Crimes 2019-2020",
                 x="",
                 y="",
                 fill='Race',
                 caption = "Source: Massachusetts Arrest Data") + 
      theme(axis.text.y =element_blank())
basecat6
```

### Num-Num Visualization 
```{r}
COVID <- read.csv("covid-19.csv")

#install.packages("lubridate")
library(lubridate)

COVID$MonthYear <- make_date(year = COVID$year, month = COVID$month)

covid_monthly <- aggregate(
  cbind(daily_cases_mean, daily_deaths_mean) ~ MonthYear,
  data = COVID,
  FUN = mean
)
min <- as.Date("2020-01-01")
max <- as.Date("2024-12-01")

library(tidyr)

covid_long <- covid_monthly %>%
  pivot_longer(cols = c(daily_cases_mean, daily_deaths_mean),
               names_to = "Metric",
               values_to = "Value")

COVIDplot <- ggplot(covid_long, aes(x = MonthYear, y = Value, color = Metric)) +
  geom_line() +
  theme_light() + 
  scale_x_date(limits = c(min, max), date_breaks = "3 months", date_labels = "%Y-%m") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_y_log10(labels = scales::comma) + 
  labs(title = "COVID Mean Cases and Deaths by Month",
                 subtitle = "Global Means Jan 2020 - Jan 2025",
                 x="Month & Year",
                 y="Log Value",
                 caption = "Source: COVID-19 data")

COVIDplot

```


### Num-Cat Visualization 
```{r}

summaryBy <- aggregate(
  Age ~ `Arrest Type`,
  data = Mass_Arrests,
  FUN = function(x) c(median = median(x), min = min(x), max = max(x))
)

summaryBy=do.call(data.frame,summaryBy)

names(summaryBy)=c('Type','median','min', 'max')



summaryBy_long <- summaryBy %>%
  pivot_longer(
    cols = -Type,           
    names_to = "stat",      
    values_to = "age"     
  )

summaryBy_long$Type <- recode(summaryBy_long$Type,
                               "F" = "Felony",
                               "M" = "Misdemeanor",
                               "W" = "Warrant", 
                               "O" = "Other")
  

catnum <- ggplot(summaryBy_long, aes(x = Type, y = age, color = stat)) + 
  geom_segment(aes(x = Type, xend = Type, y = 0, yend = age),
               color = "grey50") +
  geom_point(size = 5) +
  geom_text(aes(label = round(age,1)),
            hjust = .7, vjust = -0.85, 
            size = 4, fontface = "bold", show.legend = FALSE) +
  scale_color_manual(values = c("min" = "blue", "median" = "black", "max" = "red")) +
  facet_grid(~stat) + 
  coord_flip() + 
  theme_light() +
  ylab("Age") +
  xlab("Arrest Type") +
  ggtitle("Min, Median, and Max Age by Arrest Type") +
  labs(subtitle = "Massachusetts Crimes 2019-2020",  caption = "Source: Massachusetts Arrest Data" )

catnum
```


### Improved Plots 
-----------------------
```{r}
safeALL <- read_xlsx("safeCities_ecoUI.xlsx")
drop=c("Overall_Score")
keep=setdiff(names(safeALL),drop)
safe = safeALL[,keep]

#install.packages("reshape2")
library(reshape2)

safeL=melt(safe, # all the data
           id.vars = 'city') # unique id per row
safeL$type=ifelse(grepl("_In_",safeL$variable),'input','output')

safeL$variable=sub("_In_|_Out_",'_',safeL$variable)

safeL$dimension=substr(safeL$variable, 1, 1)
safeL$variable=gsub("^[A-Z]_", "", safeL$variable)

safe_avg = aggregate(value ~ city + type + dimension, 
                            data = safeL, 
                            FUN = mean, 
                            na.rm = TRUE)

newLevels=c('DIGI','ENVIR','HEALTH','INFRA','PERS')
safe_avg$dimension=factor(safe_avg$dimension,
                          levels = c("D","E","H","I","P"),
                          labels = newLevels,ordered = F)

safe_avg_out=safe_avg[safe_avg$type=='output',]
safe_avg_in=safe_avg[safe_avg$type=='input',]

base_ave_out= ggplot(data = safe_avg_out)

vars_ave_out=base_ave_out + aes(x = reorder(dimension,
                                          value,median),
                              y =reorder(city,
                                         value,
                                         median))

geoms_ave_out=vars_ave_out + geom_tile(aes(fill = value))

originalplotcities <- geoms_ave_out + 
       scale_fill_gradient(low = 'white',
                           high = "black") +
       theme(axis.text.x = element_text(angle = 90,
                                        hjust = 1,
                                        size = 8),
             axis.text.y = element_text(size = 6)) + labs(x="",y='')
originalplotcities

safe_avg_out <- safe_avg_out %>%
  group_by(city) %>%
  mutate(avg = mean(value)) %>%
  ungroup()

safe_avg_out$city <- reorder(safe_avg_out$city, safe_avg_out$avg)

cutoff <- quantile(safe_avg_out$value, 0.95, na.rm = TRUE)

improvedplotcities <- geoms_ave_out + 
        scale_fill_viridis_c(option = "cividis", name = "Score") +
       theme(axis.text.x = element_text(angle = 90,
                                        hjust = 1,
                                        size = 8),
             axis.text.y = element_text(size = 6)) + labs(x="",y='') + 
      scale_x_discrete(labels = c(
  ENVIR = "Environment",
  DIGI = "Digital",
  PERS = "Personal",
  INFRA = "Infrastructure",
  HEALTH = "Health"
)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  theme(
    panel.grid = element_blank(),
    axis.title = element_blank()
  ) + labs(title = "Safety of Countries Based on 5 Dimensions",
                 x="",
                 y="",
                 caption = "Source: Safe Cities Data" ) + 
   geom_text(
    aes(label = ifelse(value >= cutoff, round(value, 0), "")),
    size = 2.5, 
    color = "black"
  )
improvedplotcities

```


